// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTMIMmcIO03fOrFF4fV4lMb68Mv6lgwQ',
    appId: '1:689181377871:web:28d52b30199ca34158313a',
    messagingSenderId: '689181377871',
    projectId: 'pathforge-roadmap',
    authDomain: 'pathforge-roadmap.firebaseapp.com',
    storageBucket: 'pathforge-roadmap.firebasestorage.app',
    measurementId: 'G-2Q8KYV4MZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkJuCZDWzzcJqDWzI4oAnieZecE5WjHc',
    appId: '1:689181377871:android:1086b80af4f209ed58313a',
    messagingSenderId: '689181377871',
    projectId: 'pathforge-roadmap',
    storageBucket: 'pathforge-roadmap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3npZwmK1im4ieWUKAH1pOdbcWdOinoF8',
    appId: '1:689181377871:ios:a08323231163fdab58313a',
    messagingSenderId: '689181377871',
    projectId: 'pathforge-roadmap',
    storageBucket: 'pathforge-roadmap.firebasestorage.app',
    iosBundleId: 'com.example.pathforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3npZwmK1im4ieWUKAH1pOdbcWdOinoF8',
    appId: '1:689181377871:ios:a08323231163fdab58313a',
    messagingSenderId: '689181377871',
    projectId: 'pathforge-roadmap',
    storageBucket: 'pathforge-roadmap.firebasestorage.app',
    iosBundleId: 'com.example.pathforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYTMIMmcIO03fOrFF4fV4lMb68Mv6lgwQ',
    appId: '1:689181377871:web:236901503f4c90d258313a',
    messagingSenderId: '689181377871',
    projectId: 'pathforge-roadmap',
    authDomain: 'pathforge-roadmap.firebaseapp.com',
    storageBucket: 'pathforge-roadmap.firebasestorage.app',
    measurementId: 'G-P9B008CVCY',
  );
}
